---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: "${JWT_SECRET}"
default_redirection_url: https://lightworks.dev/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: "${TLS_KEY}"
    certificate: "${TLS_CERT}"

log:
  level: info

totp:
  issuer: lightworks.dev
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain:
        - "identity.lightworks.dev"
      policy: bypass
    - domain:
        - "mc.lightworks.dev"
      policy: one_factor
    - domain:
        - "docker.lightworks.dev"
      policy: one_factor

session:
  name: authelia_session
  domain: lightworks.dev
  same_site: lax
  secret: "${SESSION_SECRET}"
  expiration: 6h
  inactivity: 1h
  remember_me_duration: 1M
  redis:
    host: redis
    port: 6379
    password: "${REDIS_PASSWORD}"
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 4
  find_time: 10m
  ban_time: 6h

storage:
  encryption_key: "${STORAGE_ENCRYPTION_KEY}"
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia
    password: "${MYSQL_PASSWORD}"

notifier:
  disable_startup_check: false
  smtp:
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    host: smtp.gmail.com
    port: 587
    sender: "${SMTP_SENDER}"
    identifier: localhost
    subject: "[Authelia] Service Request from Authelia"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
