version: '3.8'

services:
  authelia:
    image: authelia/authelia
    container_name: Authelia
    entrypoint:
      - /app/entrypoint.sh
    working_dir: /app
    restart: "no"
    shm_size: 64mb
    pids_limit: 2048
    healthcheck:
      test: ["CMD-SHELL", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 3s
      start_period: 60s
    environment:
      PUID: "99"
      PGID: "100"
    volumes:
      - /mnt/user/appdata/Authelia:/config:rw
    ports:
      - "9091:9091"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    networks:
      proxt_net0:
        ipv4_address: ${AUTHELIA_CONTAINER_IP}

networks:
  proxt_net0:
    external: true
