version: '3.8'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    entrypoint:
      - /opt/bitnami/scripts/redis/entrypoint.sh
    command:
      - /opt/bitnami/scripts/redis/run.sh
    restart: "no"
    shm_size: 64mb
    pids_limit: 2048
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_EXTRA_FLAGS: "--auto-aof-rewrite-percentage 100 --auto-aof-rewrite-min-size 64mb"
    volumes:
      - /mnt/user/appdata/redis:/bitnami/redis:rw
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    networks:
      backend_net:
        ipv4_address: ${REDIS_CONTAINER_IP}

networks:
  backend_net:
    external: true
