version: '3.8'

services:
  ghost:
    image: ghost
    container_name: Ghost
    entrypoint:
      - docker-entrypoint.sh
    command:
      - node
      - current/index.js
    working_dir: /var/lib/ghost
    restart: "no"
    shm_size: 64mb
    pids_limit: 2048
    environment:
      database__connection__password: ${GHOST_DB_CONNECT_PWD}
      mail__transport: "SMTP"
      mail__options__auth__user: ${GHOST_MAIL_USER}
      database__client: "mysql"
      database__connection__host: "mariadb"
      url: "https://blog.lightworks.dev"
      mail__options__service: "GMail"
      database__connection__user: ${GHOST_DB_CONNECT_USER}
      mail__options__auth__pass: ${GHOST_MAIL_APP_PWD}
      database__connection__database: ${GHOST_DB_CONNECT_DATABASE}
    volumes:
      - /mnt/user/app_data/ghost:/var/lib/ghost/content:rw
    ports:
      - "2368:2368"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    networks:
      proxt_net0:
        ipv4_address: ${GHOST_CONTAINER_IP}

networks:
  proxt_net0:
    external: true
